### ISSUE TITLE
max_web_pdf_preview error

### ISSUE THREAD

**Issue by JuanJoseGomez** [maxodoo/max-misc-addons#8]
Error in max_web_pdf_preview.js:
pyeval is not defined.

I think it needs a definition line like:
var pyeval = require('web.pyeval');

After correcting this, another error appears when printing reports (depending on web browser?):

`Traceback:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (http://localhost:8069/web/content/386-3e3cd82/web.assets_common.js:3037:379)
    at HTMLIFrameElement.dispatch (http://localhost:8069/web/content/386-3e3cd82/web.assets_common.js:637:451)
    at HTMLIFrameElement.elemData.handle (http://localhost:8069/web/content/386-3e3cd82/web.assets_common.js:610:173)`

Regards,

Juanjo

**Comment by jlzhou** [comment]
Have you installed all necessary lib on your server? We do not meet this issue while using this module.

**Comment by extrememicro** [comment]
pyeval is required when py3o reporting engine from OCA is installed.
